# This workflow needs to be present in the default branch before it can be triggered (https://github.com/orgs/community/discussions/25288)
# This workflow will not appear in the PR overview. Please check "Actions" section of the GitHub repository.
name: GitHub Release

on: 
  workflow_run:
    workflows: [Build & Test, Cross-Plattform Build & Test]
    branches: [main]
    types: [completed]

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      project_name: "DDK"

    steps:
    - uses: actions/checkout@v3

    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        workflow_conclusion: success
        skip_unpack: false
  
    - name: Download artifact (cross-compiled)
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: cross-compile.yml
        workflow_conclusion: success
        skip_unpack: false

    - name: Get current semver
      run: semver=$(awk -v project="$project_name" '$0 ~ project{flag=1;next} /VERSION/{if(flag) print $2} {flag=0}' CMakeLists.txt)
        && echo "semver=v$semver" >> $GITHUB_ENV

    - name: Generate Changelog
      run: git log -1 --pretty=%B > ${{ github.workspace }}-CHANGELOG.txt

    - name: Setup local git config
      run: git config --local user.email "bot@create-release.yml"
        && git config --local user.name "GitHub Workflow"

    - name: Set git tag
      run: git tag -fa "$semver" -F ${{ github.workspace }}-CHANGELOG.txt
    
    - name: Push git tag
      run: git push -f --tags
    
    - name: export semver as workflow input variable
      run: echo ::set-output name=semver::$semver
      id: version

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        # name: ${{ steps.version.outputs.semver }}
        # body_path: ${{ github.workspace }}-CHANGELOG.txt
        generate_release_notes: true
        tag_name: ${{ steps.version.outputs.semver }}
        files: ./artifact/*
