name: Formatting Source Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install cmake-format
      run: sudo pip install cmake-format

    - name: Run cmake-format
      run: cmake-format --version
          && cmake-format -c ./.cmake-format.py -i $(find . -type f -name "*.cmake" -not -path "./externals/*")
          && cmake-format -c ./.cmake-format.py -i $(find . -type f -name "CMakeLists.txt" -not -path "./externals/*")
          && git diff --exit-code

    - name: Install clang-format
      run: sudo apt-get update -q && sudo apt-get install clang-format -q -y
    
    - name: Run clang-format
      run: clang-format --version
          && clang-format -i $(find . -type f -name "*.c" -not -path "./externals/*")
          && clang-format -i $(find . -type f -name "*.cpp" -not -path "./externals/*")
          && clang-format -i $(find . -type f -name "*.h" -not -path "./externals/*")
          && clang-format -i $(find . -type f -name "*.hpp" -not -path "./externals/*")
          && git diff --exit-code
