
# Small placeholder workflow
name: GitHub Release

on: 
  workflow_run:
    workflows: ["Build & Test"]
    types: 
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:    
      - name: Debug
        run: find .